#!/bin/sh

if [ ! -d "${HOME}/.cache/public-inbox" ]; then
	touch down
	exit 1
fi

exec snooze -H'*' -M/10 sh -c "
	git -C '$HOME/.cache/public-inbox/git/git/0.git' fetch
	public-inbox-index '$HOME/.cache/public-inbox/git'
"
