#!/bin/sh

if [ ! -d "${HOME}/.cache/public-inbox" ]; then
	touch down
	exit 1
fi

exec snooze -H'*' -M 17 -S45 sh -c '
	git -C ~/.cache/public-inbox/git/git/0.git fetch &&
	public-inbox-index ~/.cache/public-inbox/git
'
