#!/bin/sh

BROWSER=firefox
export BROWSER

## X resources
xrdb -merge "${HOME}/.config/Xresources/config" || true

## Disable Touchpad if exists
if command -v xinput >/dev/null; then
	xinput --list |
		sed -nE 's/^.*Touch[Pp]ad[[:space:]]+id=([[:digit:]]+).*$/\1/p' |
		xargs -L 1 xinput --disable
fi

_JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_AWT_WM_NONREPARENTING

if command -v fcitx >/dev/null; then
	GTK_IM_MODULE=fcitx
	QT_IM_MODULE=fcitx
	XMODIFIERS=@im=fcitx
	export GTK_IM_MODULE QT_IM_MODULE XMODIFIERS
	fcitx
fi

# xmodmap - <<EOF
# remove Lock = Caps_Lock
# remove Control = Control_L
# keysym Control_L = Caps_Lock
# keysym Caps_Lock = Control_L
# add Lock = Caps_Lock
# add Control = Control_L
# remove mod4 = Hyper_L
# EOF

# here come the madness
# capslock will send:
# - escape when press-and-released
# - ctrl when press with other keys
setxkbmap -option ctrl:nocaps -option shift:both_capslock -option nbsp:level2
xcape -e 'Control_L=Escape'

## Turn off the bell
xset -b s 180 120

xsetroot -solid '#1d2021'
nitrogen --restore

xdotool mousemove 0 10000 || true

# command -v unclutter >/dev/null 2>&1 && unclutter &

if command -v dunst >/dev/null 2>&1; then
	dunst &
fi

if [ -d /sys/class/power_supply/BAT0 ]; then
	if command -v sv >/dev/null 2>&1; then
		sv up ~/.local/service/battery
	fi
fi

if command -v start-pulseaudio-x11 >/dev/null 2>&1; then
	start-pulseaudio-x11
fi

# LXDM doesn't source .xinitrc, LXDM will set DESKTOP_SESSION
if [ "${DESKTOP_SESSION:-dwm}" = dwm ]; then
	## lock is the screensaver
	command -v sv >/dev/null 2>&1 &&
	command -v xss-lock >/dev/null 2>&1 &&
	sv up ~/.local/service/i3lock
	sv up ~/.local/service/slstatus
fi

## Hook, should be the last one to be sourced
test -r ~/.config/local.xprofile && . ~/.config/local.xprofile
