#!/bin/sh

if command -v qutebrowser >/dev/null; then
	BROWSER=qutebrowser
else
	BROWSER=firefox
fi
export BROWSER

if ! command -v sv >/dev/null; then
	sv() { :; }
fi

## X resources
if command -v xrdb >/dev/null
then
	xrdb -merge "${HOME}/.config/Xresources/config"
	if [ -f "$HOME/.config/Xresources/local" ]
	then
		xrdb -merge "${HOME}/.config/Xresources/local"
	fi
fi


_JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_AWT_WM_NONREPARENTING

if command -v fcitx >/dev/null; then
	GTK_IM_MODULE=fcitx
	QT_IM_MODULE=fcitx
	XMODIFIERS=@im=fcitx
	export GTK_IM_MODULE QT_IM_MODULE XMODIFIERS
	fcitx
fi

# xmodmap - <<EOF
# remove Lock = Caps_Lock
# remove Control = Control_L
# keysym Control_L = Caps_Lock
# keysym Caps_Lock = Control_L
# add Lock = Caps_Lock
# add Control = Control_L
# remove mod4 = Hyper_L
# EOF

# here come the madness
# capslock will send:
# - escape when press-and-released
# - ctrl when press with other keys
setxkbmap -option ctrl:nocaps -option shift:both_capslock -option nbsp:level2
command -v xcape >/dev/null &&
xcape -e 'Control_L=Escape'

## Turn off the bell
xset -b s 180 120

if ! command -v feh >/dev/null; then
	xsetroot -solid '#1d2021'
elif test -f ~/Pictures/wallpaper.png; then
	feh --bg-center ~/Pictures/wallpaper.png
elif test -f ~/Pictures/wallpaper.jpg; then
	feh --bg-center ~/Pictures/wallpaper.jpg
elif test -f ~/Pictures/wallpaper.jpeg; then
	feh --bg-center ~/Pictures/wallpaper.jpeg
fi

xdotool mousemove 0 10000 || true

# command -v unclutter >/dev/null 2>&1 && unclutter &

if command -v dunst >/dev/null 2>&1; then
	dunst &
fi

if [ -d /sys/class/power_supply/BAT0 ]; then
	sv up ~/.local/service/battery
fi

if command -v start-pulseaudio-x11 >/dev/null 2>&1; then
	start-pulseaudio-x11
fi

# LXDM doesn't source .xinitrc, LXDM will set DESKTOP_SESSION
case "${DESKTOP_SESSION:-i3}" in
i3|xinitrc)
	## lock is the screensaver
	sv up ~/.local/service/i3lock
	;;
esac

# if command -v urxvtd >/dev/null; then
# 	export RXVT_SOCKET=$HOME/.cache/urxvt/urxvt.socket
# 	mkdir ${RXVT_SOCKET%/*}
# 	urxvtd -q -f -o
# fi

## Hook, should be the last one to be sourced
test -r ~/.config/local.xprofile && . ~/.config/local.xprofile
