#!/bin/sh
#
# Kernel hook for efibootmgr.
#
# Arguments passed to this script: $1 pkgname, $2 version.
#
VERSION="$2"

. "${ROOTDIR}/etc/default/efibootmgr-kernel-hook"
if [ "x${MODIFY_EFI_ENTRIES}" != x2 ]; then
	exit 0
fi

xversion=$(echo "$VERSION" | sed 's/[.]/[.]/g')

# get hex number of the matching entry
entry=$(efibootmgr |
	sed -n "s/^Boot\\(....\\).*Void Linux with kernel ${xversion}/\\1/p")
test -z "$entry" || efibootmgr -Bq -b "$entry"
