#!/bin/sh

exec 2>&1

[ -f conf ] && . conf

: ${ZUSER:=danh}

[ $? -eq 0 ] || exit

ZHOME=$(eval echo ~$ZUSER)

install -d -m 700 -o $ZUSER -g $ZUSER /run/x-user/$ZUSER
install -d -m 700 -o $ZUSER -g $ZUSER /run/x-user/$ZUSER/runit

exec chpst -u$ZUSER:$ZUSER runsvdir "$ZHOME/.local/service"
