#!/bin/sh

exec 2>&1

[ -f conf ] && . conf

: ${ZUSER:=sgn}

install -d -m 700 -o $ZUSER -g $ZUSER /run/x-user/$ZUSER
install -d -m 700 -o $ZUSER -g $ZUSER /run/x-user/$ZUSER/runit

export HOME=$(eval echo ~$ZUSER)
[ $? -eq 0 ] || exit
groups=$(id -Gn $ZUSER | tr ' ' ':')

exec chpst -u"$ZUSER:$groups" sh -l -c '
	cd ~
	if [ -f ~/.local/runit-user.local ]; then
		. ~/.local/runit-user.local
	fi
	exec runsvdir ~/.local/service
'
