#!/bin/sh
#
# Kernel hook for efibootmgr.
#
# Arguments passed to this script: $1 pkgname, $2 version.
#
VERSION="$2"

. "${ROOTDIR}/etc/default/efibootmgr-kernel-hook"
if [ "x${MODIFY_EFI_ENTRIES}" != x2 ]; then
	exit 0
fi

OPTIONS="${OPTIONS} initrd=/initramfs-${VERSION}.img"

args=""
if [ "x${DISK}" != x ]; then
	args="-d $DISK"
fi

# if existing, do nothing
if efibootmgr | grep -q -F "Void Linux with kernel ${VERSION}"; then
	exit 0
fi

# create the new entry
efibootmgr -qc $args \
	-L "Void Linux with kernel ${VERSION}" \
	-l /vmlinuz-${VERSION} \
	-u "${OPTIONS}"
